version: '3.8'

services:
  balzer-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: balzer_web
    restart: unless-stopped
    ports:
      - "3010:3010"
    env_file:
      - .env
    volumes:
      - ./public/uploads:/app/public/uploads
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true
